---
apiVersion: v1
kind: Pod
metadata:
    name: javawebapp
    labels:
        app: javawebapp
spec:
    containers:
        - name: javawebappcontainer
          image: hacker123shiva/springbt-in-docker:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: javawebappsvc
spec:
    type: LoadBalancer
    selector:
        app: javawebapp
    ports:
        - port: 80
          targetPort: 8080
...
