---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  containers:
    - name: javawebappcontainer
      image: edydockers/sms-frontend:dev-31
      ports:
        - containerPort: 80
...
