---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template: 
    metadata:
      name: javawebpod 
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: hacker123shiva/springbt-in-docker:latest
          ports:
           - containerPort: 8080
...

