---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-db-config-map        # Name of the ConfigMap
  labels:
    storage: demo-db-storage      # Optional: label for categorization or selection
data:
  DB_HOST_SERVICE_NAME_VALUE: demo-app-db-service
  DB_SCHEMA_VALUE: demo-mkdapp
  DB_PORT_VALUE: "3306"
  DB_URL: jdbc:mysql://demo-app-db-service:3306/demo-mkdapp
...

