---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-db-pvc
spec:
  volumeName: demo-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage

...
