---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebbluedeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: java-web-app
      version: v1
      color: blue
  template:
    metadata:
      labels:
        app: java-web-app
        version: v1
        color: blue
    spec:
      containers:
        - name: javawebappcontainer
          image: hacker123shiva/springbt-in-docker:latest
          imagePullPolicy: Always
          ports:
           - containerPort: 8080
...
