---
apiVersion: v1
kind: Service
metadata:
    name: javawebapplivesvc
spec:
    type: LoadBalancer
    selector:
        app: java-web-app # Matches the app
        color: blue # Sends traffic to the blue pods
          #color: green
    ports:
        - port: 80
          targetPort: 8080
...
