---
apiVersion: v1
kind: Service
metadata:
    name: javaprepodsvc
spec:
    type: NodePort
    selector:
        app: javawebapp
        color: green
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
          nodePort: 31785 # Optional: remove this if you want auto-assign port
...
