---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-db-pv
  labels:
    name: demo-db-pv
spec:
  capacity:
    storage: 4Gi                         # 4 GiB of storage
  accessModes:
    - ReadWriteOnce                      # Only one node can mount it read-write
  persistentVolumeReclaimPolicy: Retain # Keeps the data even after PVC is deleted
  storageClassName: local-storage       # Must match with the PVC's storageClassName
  hostPath:
    path: /opt/mysql
...
