apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
  labels:
    k8s-app: fluentd
data:
  fluent.conf: |
    @type forward
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    <filter **>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      logstash_format true
      include_tag_key true
      type_name access_log
      flush_interval 5s
    </match>

