apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: efklog
  labels:
    app: kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: http
      protocol: TCP
      port: 5601
      targetPort: 5601

