---
- hosts: webservers
  become: true
  tasks:
    - name: Install httpd package in only Managed node1
      yum:
        name: httpd
        state: latest

    - name: Copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start httpd server
      service: 
        name: httpd
        state: started
      
...

